name = "openai/gpt-oss-20b"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.03
output = 0.14

[limit]
context = 131000
output = 32768

[modalities]
input = ["text"]
output = ["text"]
