name = "nvidia/llama-3.3-70b-instruct-fp8"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.12
output = 0.38

[limit]
context = 131072
output = 16384

[modalities]
input = ["text"]
output = ["text"]
