name = "Holo3 122B A10B"
attachment = true
reasoning = false
tool_call = false
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.4
output = 3

[limit]
context = 65536
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
