name = "holo2-30b-a3b"
attachment = true
reasoning = false
tool_call = true
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.3
output = 0.7

[limit]
context = 22000
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
