name = "meta.llama3-1-405b-instruct-v1:0"
attachment = false
reasoning = false
tool_call = true
structured_output = false
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 2.4
output = 2.4

[limit]
context = 128000
output = 4096

[modalities]
input = ["text"]
output = ["text"]
