name = "us.amazon.nova-lite-v1:0 (US)"
attachment = true
reasoning = false
tool_call = true
structured_output = false
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.06
output = 0.24
cache_read = 0.015

[limit]
context = 300000
output = 8192

[modalities]
input = ["text", "image", "video"]
output = ["text"]
