name = "qwen/qwen3-235b-a22b-2507"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.072
output = 0.464

[limit]
context = 131000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
