name = "openai/gpt-oss-safeguard-20b"
attachment = false
reasoning = true
tool_call = true
structured_output = false
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.075
output = 0.3
cache_read = 0.037

[limit]
context = 131072
output = 65536

[modalities]
input = ["text"]
output = ["text"]
