name = "gpt-4o-mini-transcribe"
attachment = false
reasoning = false
tool_call = false
temperature = true
knowledge = "2024-06"
release_date = "2024-10"
last_updated = "2024-10"
open_weights = false

[cost]
input = 1.25
output = 5

[limit]
context = 16000
output = 2000

[modalities]
input = ["text", "audio"]
output = ["text"]
