name = "gpt-4.1-nano-2025-04-14"
attachment = true
reasoning = false
tool_call = true
temperature = true
release_date = "2025-04"
last_updated = "2025-04"
open_weights = false

[cost]
input = 0.1
output = 0.4

[limit]
context = 1047576
output = 16384

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
