name = "o4-mini-2025-04-16"
attachment = false
reasoning = true
tool_call = true
temperature = true
knowledge = "2023-10"
release_date = "2024-05"
last_updated = "2024-05"
open_weights = false

[cost]
input = 1.1
output = 4.4

[limit]
context = 200000
output = 32768

[modalities]
input = ["text"]
output = ["text"]
