name = "meta-llama/llama-prompt-guard-2-22m"
attachment = false
reasoning = false
tool_call = false
structured_output = false
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.03
output = 0.03

[limit]
context = 512
output = 512

[modalities]
input = ["text"]
output = ["text"]
