name = "z-ai/glm-4.6"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.4
output = 1.75

[limit]
context = 203000
output = 131000

[modalities]
input = ["text"]
output = ["text"]
