name = "grok-4.20-multi-agent-beta-latest"
attachment = true
reasoning = true
tool_call = false
structured_output = false
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.2

[limit]
context = 2000000
output = 30000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
