name = "MiniMax-M2.5-lightning"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2026-02"
last_updated = "2026-02"
open_weights = false

[cost]
input = 0.3
output = 2.4

[limit]
context = 204800
output = 204800

[modalities]
input = ["text"]
output = ["text"]
