name = "MiniMax-M2"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2026-02"
last_updated = "2026-02"
open_weights = false

[cost]
input = 0.3
output = 1.2

[limit]
context = 196608
output = 128000

[modalities]
input = ["text"]
output = ["text"]
