name = "compound-mini"
attachment = false
reasoning = true
tool_call = true
structured_output = false
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 131072
output = 8192

[modalities]
input = ["text"]
output = ["text"]
