name = "deepseek/deepseek-chat-v3.1"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.2
output = 0.8

[limit]
context = 164000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
