name = "deepseek/deepseek-r1-0528"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-03"
last_updated = "2026-03"
open_weights = false

[cost]
input = 0.66
output = 2.6

[limit]
context = 164000
output = 8192

[modalities]
input = ["text"]
output = ["text"]
