name = "magistral-small-2509"
attachment = true
reasoning = false
tool_call = true
temperature = true
release_date = "2025-11"
last_updated = "2025-11"
open_weights = false

[cost]
input = 0.5
output = 1.5

[limit]
context = 131072
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
