name = "MiniMaxAI/MiniMax-M2.5"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-04"
last_updated = "2026-04"
open_weights = false

[cost]
input = 0.24
output = 0.9

[limit]
context = 196608
output = 16384

[modalities]
input = ["text"]
output = ["text"]
